### ISSUE TITLE
ALLOW_LIST_BUCKET=false does not apply to subdirectories

### ISSUE THREAD

**Issue by jonhoo** [backblaze-b2-samples/cloudflare-b2#12]
I assume this is intentional, but it was surprising behavior to me at least! Would be worth documenting.

Also, skimming the code, I'm not sure the return-404 handling does the right thing when there are `../`s in the path.

**Comment by jonhoo** [comment]
Or perhaps this is a misunderstanding on my part and only requests for the root will actually list?

**Comment by metadaddy** [comment]
It's useful to draw the distinction between the S3 API and the way a web server behaves. Directories don't really exist in the S3 API. `/` characters are just part of the object key (file name). The 'path' to a file is really just a prefix of the object key.

In the S3 API, you list bucket contents by performing a GET on the bucket URL, e.g. `https://acme-images.s3.us-west-001.backblazeb2.com/`.

If you want to restrict the listing to objects with a given prefix, rather than appending a path to the URL, as in `https://acme-images.s3.us-west-001.backblazeb2.com/some/path/`, you supply a `prefix` query parameter, e.g. `https://acme-images.s3.us-west-001.backblazeb2.com/?prefix=/some/path/`.

In the S3 API, if you do try to GET a URL of the form `https://acme-images.s3.us-west-001.backblazeb2.com/some/path/`, you are asking for an object with the key `/some/path/`, and the request will likely fail with error 404.

Also, dots are just part of the object key, rather than indicating file system traversal, so I think everything here is operating as expected.
